# Generated by Django 5.2.7 on 2025-10-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_project_video_url_alter_project_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tu nombre completo o profesional', max_length=100)),
                ('title', models.CharField(help_text='Ejemplo: Desarrollador Web / Diseñador Multimedia', max_length=150)),
                ('description', models.TextField(help_text='Una breve descripción sobre ti, tu experiencia o enfoque profesional')),
                ('photo', models.ImageField(blank=True, help_text='Foto de perfil o retrato profesional', null=True, upload_to='profile/')),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('behance', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('cv_file', models.FileField(blank=True, help_text='Archivo PDF con tu hoja de vida', null=True, upload_to='profile/cv/')),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Solo un perfil debe estar activo')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfil',
                'ordering': ['name'],
            },
        ),
    ]
